app = "rainbow-community"
primary_region = "nrt"

[build]

[env]
  PORT = "8000"
  FLY_APP_NAME = "rainbow-community"
  MEDIA_DIR = "/data/media"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

[[http_service.checks]]
  grace_period = "10s"
  interval = "30s"
  method = "GET"
  timeout = "5s"
  path = "/healthz"

[[services.checks]]
  type = "http"
  interval = "15s"
  timeout = "2s"
  path = "/healthz"

[machine]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[[statics]]
  guest_path = "/app/static"
  url_prefix = "/static/"

[[mounts]]
  source = "data"
  destination = "/data"
