
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE orientations TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE genders TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE pronouns TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE users TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE profiles TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE media_assets TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE posts TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE comments TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE tags TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE post_tags TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE follows TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE reactions TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE notifications TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE reports TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE blocks TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE content_items TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE reviews TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE point_events TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE awards TO app_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON TABLE user_awards TO app_user;

GRANT USAGE, SELECT, UPDATE ON SEQUENCE orientations_id_seq TO app_user;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE genders_id_seq TO app_user;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE pronouns_id_seq TO app_user;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE users_id_seq TO app_user;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE media_assets_id_seq TO app_user;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE posts_id_seq TO app_user;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE comments_id_seq TO app_user;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE tags_id_seq TO app_user;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE reactions_id_seq TO app_user;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE notifications_id_seq TO app_user;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE reports_id_seq TO app_user;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE content_items_id_seq TO app_user;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE reviews_id_seq TO app_user;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE point_events_id_seq TO app_user;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE awards_id_seq TO app_user;
GRANT USAGE, SELECT, UPDATE ON SEQUENCE user_awards_id_seq TO app_user;

ALTER DEFAULT PRIVILEGES FOR ROLE dbadmin IN SCHEMA public 
    GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO app_user;

ALTER DEFAULT PRIVILEGES FOR ROLE dbadmin IN SCHEMA public 
    GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO app_user;

REVOKE CREATE ON SCHEMA public FROM app_user;
