name: API CI

on:
  pull_request:
    paths:
      - 'backend/**'
      - '.github/workflows/api-ci.yml'
  push:
    branches: [ main, develop, 'devin/**' ]
    paths:
      - 'backend/**'
      - '.github/workflows/api-ci.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@localhost:5432/test_db
      SECRET_KEY: test-secret-key
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_MINUTES: 10080

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: |
          pip install poetry
          poetry --version

      - name: Install dependencies
        working-directory: backend
        run: poetry install

      - name: Wait for Postgres
        run: |
          for i in {1..20}; do
            pg_isready -h localhost -p 5432 -U postgres && break
            sleep 2
          done

      - name: Run Alembic migrations
        working-directory: backend
        run: poetry run alembic upgrade head

      - name: Run tests
        working-directory: backend
        run: poetry run pytest -v

      - name: Check if tests passed
        if: failure()
        run: echo "Tests failed. Please check the output above."
